### PR TITLE
Fix 3 bugs reported on discord

### LINKED ISSUE #329: [Bug]: divide by 0 in patchouli book
### Describe the bug

Minecraft dies when I try to open the altar section in the book that explains everything.

### Steps to Reproduce

Just try open the third page in the altar section

### Expected behavior

I just wanna have it fixed or, if you can, a screenshot of the pages after the second page to build my altar 

### Screenshots

image

### Version

1.19.2-1.1.5

### Forge Version

1.19.2 (43.1.1)

### Other Mods

I´ve tried it without other mods 

### Log

_No response_

### PR DESCRIPTION
**Pull request by Minecraftschurli**
- Fixes divide by 0 in patchouli book (fixes #329)
- Fixes altar core not updating camo state correctly
- Fixes `KnowledgeHolder#skillPoints` being immutable

### CODE REVIEW

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/compat/patchouli/PatchouliCompat.java [hunk 1]
```diff
@@ -291,6 +299,14 @@ public void init(FMLCommonSetupEvent event) {
         ).setSymmetrical(true));
     }
 
+    @NotNull
```
Comment (IchHabeHunger54) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/compat/patchouli/PatchouliCompat.java]: Unnecessary NotNull, we assume non-nullability unless explicitly stated (if not, add the package-info for that package).

**Review by IchHabeHunger54 — COMMENTED** [review]
2 things:
a) remove the NotNull annotation
b) why the static imports from PatchouliCompat?

**Review by IchHabeHunger54 — APPROVED** [review]
