### PR TITLE
Add contingency shapes and fix the spell book

### LINKED ISSUE #293: Damage Contingency Shape

### LINKED ISSUE #294: Death Contingency Shape

### LINKED ISSUE #295: Fall Contingency Shape

### LINKED ISSUE #296: Fire Contingency Shape

### LINKED ISSUE #297: Health Contingency Shape

### PR DESCRIPTION
**Pull request by Minecraftschurli**
Closes #297, #296, #295, #294 and #293

### CODE REVIEW

File: src/data/java/com/github/minecraftschurlimods/arsmagicalegacy/data/AMRitualProvider.java [hunk 1]
```diff
@@ -83,63 +82,52 @@ protected void addRituals(BiConsumer<ResourceLocation, Ritual> consumer) {
...
                 .with(ItemDropRitualTrigger.item(Items.ENDER_EYE))
                 .with(new EnderDragonDimensionRequirement())
                 .with(new EntitySpawnRitualEffect(AMEntities.ENDER_GUARDIAN.get()))
                 .build(consumer);
-
         builder(new ResourceLocation(ArsMagicaAPI.MOD_ID, "spawn_ice_guardian"))
                 .with(new RitualStructureRequirement(PatchouliCompat.ICE_GUARDIAN_SPAWN_RITUAL))
                 .with(new EntitySummonTrigger(EntityType.SNOW_GOLEM))
-                /*.with(new BiomeRequirement(Tags.Biomes.IS_FROZEN))*///TODO: Add biome requirement
+//                .with(new BiomeRequirement(Tags.Biomes.IS_FROZEN))
```
Comment (Minecraftschurli) [inline src/data/java/com/github/minecraftschurlimods/arsmagicalegacy/data/AMRitualProvider.java]: why remove the todo

Comment (IchHabeHunger54) [reply src/data/java/com/github/minecraftschurlimods/arsmagicalegacy/data/AMRitualProvider.java]: I changed the comment to single-line and forgot to readd the todo

**Review by IchHabeHunger54 — DISMISSED** [review]

**Review by IchHabeHunger54 — DISMISSED** [review]

**Review by IchHabeHunger54 — APPROVED** [review]
