### PR TITLE
Miscellaneous fixes & features

### LINKED ISSUE #111: [Feature] Arcane Compendium GUI Texture

### LINKED ISSUE #118: [Feature] Lesser Mana Potion

### LINKED ISSUE #119: [Feature] Standard Mana Potion

### LINKED ISSUE #120: [Feature] Greater Mana Potion

### LINKED ISSUE #121: [Feature] Epic Mana Potion

### LINKED ISSUE #122: [Feature] Legendary Mana Potion

### LINKED ISSUE #123: [Feature] Infused Etherium Potion

### LINKED ISSUE #228: [Feature] Mana Cake

### LINKED ISSUE #229: [Feature] Mana Martini

### LINKED ISSUE #230: [Feature] Mage Armor

### LINKED ISSUE #231: [Feature] Mage Armor Repairing Mechanic

### LINKED ISSUE #232: [Feature] Battlemage Armor

### LINKED ISSUE #233: [Feature] Battlemage Armor Repairing Mechanic

### LINKED ISSUE #247: internal server error wehn dropping into the end portal
hey there so after i killed the ender dragon and wished to go back i ran into a issue XD
it seems wehn you dont start ers magicka before killing the dragon you cant use the portal somethign about couldnt found mana level of entitiy

### LINKED ISSUE #249: Inscription Table ALL ITEMS duplication [IMPORTANT]
image

Clicking with SHIFT on any item excluding writable book cause it go to upper slot and dublicate (x2)

image

Works with any item you can stack.

### PR DESCRIPTION
**Pull request by IchHabeHunger54**
This PR is for multiple features that are too small to get their own branch, plus some bugfixes, code cleanups, and documentation.

Closes #111 .
Closes #118 .
Closes #119 .
Closes #120 .
Closes #121 .
Closes #122 .
Closes #123 .
Closes #228 .
Closes #229 .
Closes #230 .
Closes #231 .
Closes #232 .
Closes #233 .
Fixes #247 .
Fixes #249 .

### CODE REVIEW

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/ArsMagicaAPI.java [hunk 1]
```diff
@@ -50,162 +47,128 @@ private ArsMagicaAPI() {
...
         @Unmodifiable
         IShrinkHelper getShrinkHelper();
 
         /**
-         * Get the {@link IEtheriumHelper} instance.
-         *
-         * @return the {@link IEtheriumHelper} instance
+         * @return The etherium helper instance.
          */
         IEtheriumHelper getEtheriumHelper();
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/ArsMagicaAPI.java:153]: Add the @Unmodifiable annotation here for consistency

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/ArsMagicaAPI.java [hunk 2]
```diff
@@ -50,162 +47,128 @@ private ArsMagicaAPI() {
...
+         * @param level  The level to open the gui in.
+         * @param player The player to open the gui for.
+         * @param stack  The spell item stack to open the gui for.
          */
         void openSpellCustomizationGui(Level level, Player player, ItemStack stack);
     }
 
-    @SuppressWarnings("ConstantConditions")
-    private static final class StubArsMagicaAPI implements IArsMagicaAPI {
+    private static class StubArsMagicaAPI implements IArsMagicaAPI {
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/ArsMagicaAPI.java:173]: Why remove the final and the warning suppression?

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/advancement/PlayerLevelUpTrigger.java [hunk 3]
```diff
@@ -24,8 +27,13 @@ public ResourceLocation getId() {
...
     }
 
+    /**
+     * Triggers the advancement trigger.
+     * @param pPlayer The affected player.
+     * @param level   The new level.
+     */
     public void trigger(ServerPlayer pPlayer, int level) {
-        this.trigger(pPlayer, (p_70648_) -> p_70648_.matches(level));
+        trigger(pPlayer, (p_70648_) -> p_70648_.matches(level));
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/advancement/PlayerLevelUpTrigger.java]: Leave the `this.` in there and change `p_70648_` to `t` for consistency

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/advancement/PlayerLevelUpTrigger.java [hunk 4]
```diff
@@ -36,15 +44,19 @@ public TriggerInstance(EntityPredicate.Composite pPlayer, MinMaxBounds.Ints leve
...
 
-        public boolean matches(int level) {
-            return this.level.matches(level);
-        }
-
         @Override
         public JsonObject serializeToJson(SerializationContext pConditions) {
             JsonObject jsonobject = super.serializeToJson(pConditions);
-            jsonobject.add("level", this.level.serializeToJson());
+            jsonobject.add("level", level.serializeToJson());
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/advancement/PlayerLevelUpTrigger.java]: Leave the `this.` in there

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/client/OcculusTabRenderer.java [hunk 5]
```diff
@@ -18,14 +18,13 @@
 import java.util.List;
 
 /**
- * Base class for all occulus tab renderers<br>
- * <p>To register a tab renderer you need to call <br>
- * {@code ArsMagicaAPI.get().registerOcculusTabRenderer(<registered occulus tab>, (occulusTab, player) -> <create your tab renderer>)}</p>
+ * Base class for all occulus tab renderers.
+ * To register a tab renderer, call {@code ArsMagicaAPI.get().registerOcculusTabRenderer(<registered occulus tab>, (occulusTab, player) -> <create your tab renderer>);}
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/client/OcculusTabRenderer.java:22]: Have you checked the resulting javadoc? Does removing the html tags still look the same in the generated javadoc?

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/AltarStructureMaterialProvider.java [hunk 6]
```diff
@@ -51,23 +52,51 @@ public void run(HashCache pCache) throws IOException {
 
     @Override
     public String getName() {
-        return "StructureMaterialProvider["+this.namespace+"]";
+        return "Altar Structure Materials";
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/AltarStructureMaterialProvider.java]: The name should be different for each instance with a different output namespace

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/AltarStructureMaterialProvider.java [hunk 7]
```diff
@@ -51,23 +52,51 @@ public void run(HashCache pCache) throws IOException {
...
+    /**
+     * Adds a new cap material.
+     *
+     * @param name  The name of the new cap material.
+     * @param cap   The block for the new cap material.
+     * @param power The power of the new cap material.
+     */
     protected void addCapMaterial(String name, Block cap, int power) {
-        addCapMaterial(new ResourceLocation(this.namespace, name), cap, power);
+        addCapMaterial(new ResourceLocation(namespace, name), cap, power);
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/AltarStructureMaterialProvider.java]: Keep the `this.`

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/AltarStructureMaterialProvider.java [hunk 8]
```diff
@@ -51,23 +52,51 @@ public void run(HashCache pCache) throws IOException {
...
+     * Adds a new structure material.
+     *
+     * @param name  The name of the new cap material.
+     * @param block The block for the new cap material.
+     * @param stair The stair block for the new cap material.
+     * @param power The power of the new cap material.
+     */
     protected void addStructureMaterial(String name, Block block, StairBlock stair, int power) {
-        addStructureMaterial(new ResourceLocation(this.namespace, name), block, stair, power);
+        addStructureMaterial(new ResourceLocation(namespace, name), block, stair, power);
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/AltarStructureMaterialProvider.java]: Keep the `this.`

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/ObeliskFuelProvider.java [hunk 9]
```diff
@@ -0,0 +1,153 @@
...
+
+    @Override
+    public void run(HashCache pCache) {
+        createFuels();
+        data.forEach((resourceLocation, jsonObject) -> save(pCache, jsonObject, generator.getOutputFolder().resolve("data/" + resourceLocation.getNamespace() + "/obelisk_fuel/" + resourceLocation.getPath() + ".json")));
+    }
+
+    @Override
+    public String getName() {
+        return "Obelisk Fuels";
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/ObeliskFuelProvider.java]: The name should be different for each instance with a different output namespace

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/OcculusTabProvider.java [hunk 10]
```diff
@@ -16,53 +15,46 @@
...
     }
 
-    /**
-     * Implement to add your own occulus tabs
-     * @param consumer provided by the datagen
-     */
-    protected abstract void createOcculusTabs(Consumer<OcculusTabBuilder> consumer);
+    @Override
+    public String getName() {
+        return "Occulus Tabs";
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/OcculusTabProvider.java]: The name should be different for each instance with a different output namespace

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/PrefabSpellProvider.java [hunk 11]
```diff
@@ -0,0 +1,97 @@
...
+        for (Map.Entry<ResourceLocation, JsonObject> entry : data.entrySet()) {
+            ResourceLocation id = entry.getKey();
+            JsonObject spell = entry.getValue();
+            DataProvider.save(GSON, pCache, spell, generator.getOutputFolder().resolve("data/" + id.getNamespace() + "/prefab_spells/" + id.getPath() + ".json"));
+        }
+    }
+
+    @Override
+    public String getName() {
+        return "Prefab Spells";
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/PrefabSpellProvider.java]: The name should be different for each instance with a different output namespace

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/PrefabSpellProvider.java [hunk 12]
```diff
@@ -0,0 +1,97 @@
...
+
+    /**
+     * Adds a new prefab spell.
+     *
+     * @param id    The id of the prefab spell.
+     * @param spell The prefab spell.
+     */
+    public void addPrefabSpell(ResourceLocation id, IPrefabSpell spell) {
+        new PrefabSpellBuilder(id, spell).build();
+    }
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/PrefabSpellProvider.java:87]: add methods that take String ids and use the namespace to create the ResourceLocation

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/PrefabSpellProvider.java [hunk 13]
```diff
@@ -0,0 +1,97 @@
...
+        public void build() {
+            data.put(id, serialize());
+        }
+
+        JsonObject serialize() {
+            JsonObject json = new JsonObject();
+            json.add("spell", spell.getEncodedSpell().getOrThrow(false, LOGGER::warn));
+            if (name != null) {
+                json.addProperty("name", name);
+            }
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/PrefabSpellProvider.java]: `this.`

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/SkillProvider.java [hunk 14]
```diff
@@ -18,58 +17,50 @@
...
+                saveSkill(pCache, skill.serialize(), generator.getOutputFolder().resolve("data/" + skill.getId().getNamespace() + "/am_skills/" + skill.getId().getPath() + ".json"));
             }
         });
     }
 
-    public Set<ResourceLocation> getSkills() {
-        return Collections.unmodifiableSet(ids);
+    @Override
+    public String getName() {
+        return "Skills";
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/SkillProvider.java]: The name should be different for each instance with a different output namespace

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/SpellPartDataProvider.java [hunk 15]
```diff
@@ -31,114 +31,104 @@
...
-        Path path = generator.getOutputFolder();
         createSpellPartData();
-        data.forEach((resourceLocation, jsonObject) -> save(pCache, jsonObject, path.resolve("data/" + resourceLocation.getNamespace() + "/spell_parts/" + resourceLocation.getPath() + ".json")));
+        data.forEach((resourceLocation, jsonObject) -> save(pCache, jsonObject, generator.getOutputFolder().resolve("data/" + resourceLocation.getNamespace() + "/spell_parts/" + resourceLocation.getPath() + ".json")));
     }
 
-    protected abstract void createSpellPartData();
+    @Override
+    public String getName() {
+        return "Spell Part Data";
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/SpellPartDataProvider.java]: The name should be different for each instance with a different output namespace

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/etherium/EtheriumType.java [hunk 16]
```diff
@@ -5,14 +5,14 @@
 import net.minecraft.resources.ResourceLocation;
 
 /**
- * The etherium types.
+ * Enum for etherium type.
  */
 public enum EtheriumType implements ITranslatable {
-    LIGHT(0xff79a5ed), NEUTRAL(0xff2effab), DARK(0xff800000);
+    LIGHT(0xff7fa7ef), NEUTRAL(0xff3fffbf), DARK(0xff800000);
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/etherium/EtheriumType.java:11]: Did you test the colors with TOP? are the bars visible?

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/event/SpellEvent.java [hunk 17]
```diff
@@ -20,15 +19,13 @@
      */
     private final ISpell spell;
 
-    public SpellEvent(@Nullable LivingEntity entity, ISpell spell) {
+    public SpellEvent(LivingEntity entity, ISpell spell) {
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/event/SpellEvent.java:20]: Why remove @Nullable?

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/event/SpellEvent.java [hunk 18]
```diff
@@ -64,67 +61,59 @@ public ManaCost(LivingEntity entity, ISpell spell) {
             public Pre(LivingEntity entity, ISpell spell, float base, float multiplier) {
                 super(entity, spell);
                 this.base = base;
-                this.modifiedBase = base;
                 this.multiplier = multiplier;
+                modifiedBase = base;
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/event/SpellEvent.java]: Keep the `this.`

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/event/SpellEvent.java [hunk 19]
```diff
@@ -64,67 +61,59 @@ public ManaCost(LivingEntity entity, ISpell spell) {
...
             /**
-             * Set the base mana cost.
+             * Sets the base mana cost.
              *
-             * @param base the new value for the base mana cost
+             * @param base The new value for the base mana cost.
              */
             public void setBase(float base) {
-                this.modifiedBase = base;
+                modifiedBase = base;
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/event/SpellEvent.java]: Keep the `this.`

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/event/SpellEvent.java [hunk 20]
```diff
@@ -64,67 +61,59 @@ public ManaCost(LivingEntity entity, ISpell spell) {
...
             /**
-             * Set the mana cost multiplier.
+             * Sets the mana cost multiplier.
              *
-             * @param multiplier the new value for the mana cost multiplier
+             * @param multiplier The new value for the mana cost multiplier.
              */
             public void setMultiplier(float multiplier) {
-                this.modifiedMultiplier = multiplier;
+                modifiedMultiplier = multiplier;
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/event/SpellEvent.java]: Keep the `this.`

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/event/SpellEvent.java [hunk 21]
```diff
@@ -133,40 +122,36 @@ public void setMultiplier(float multiplier) {
             public Post(LivingEntity entity, ISpell spell, float mana) {
                 super(entity, spell);
                 this.mana = mana;
-                this.modifiedMana = mana;
+                modifiedMana = mana;
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/event/SpellEvent.java]: Keep the `this.`

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/event/SpellEvent.java [hunk 22]
```diff
@@ -133,40 +122,36 @@ public void setMultiplier(float multiplier) {
...
             /**
-             * Set the calculated mana cost.
+             * Sets the calculated mana cost.
              *
-             * @param mana the new value for the calculated mana cost
+             * @param mana The new value for the calculated mana cost.
              */
             public void setMana(float mana) {
-                this.modifiedMana = mana;
+                modifiedMana = mana;
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/event/SpellEvent.java]: Keep the `this.`

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/event/SpellEvent.java [hunk 23]
```diff
@@ -175,44 +160,37 @@ public void setMana(float mana) {
         public BurnoutCost(LivingEntity entity, ISpell spell, float burnout) {
             super(entity, spell);
             this.burnout = burnout;
-            this.modifiedBurnout = burnout;
+            modifiedBurnout = burnout;
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/event/SpellEvent.java]: Keep the `this.`

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/event/SpellEvent.java [hunk 24]
```diff
@@ -175,44 +160,37 @@ public void setMana(float mana) {
...
         /**
-         * Set the burnout cost.
+         * Sets the burnout cost.
          *
-         * @param burnout the new value for the burnout cost
+         * @param burnout The new value for the burnout cost.
          */
         public void setBurnout(float burnout) {
-            this.modifiedBurnout = burnout;
+            modifiedBurnout = burnout;
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/event/SpellEvent.java]: Keep the `this.`

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/magic/IBurnoutHelper.java [hunk 25]
```diff
@@ -7,41 +7,40 @@
...
 
     /**
      * Sets the burnout value of the given entity.
      *
-     * @param livingEntity the entity to set the burnout value for
+     * @param entity The entity to set the burnout value for.
+     * @param amount The value to set the burnout value to.
      */
-    void setBurnout(LivingEntity livingEntity, float amount);
+    boolean setBurnout(LivingEntity entity, float amount);
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/magic/IBurnoutHelper.java:46]: What does the return do?

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/spell/ISpellIngredient.java [hunk 26]
```diff
@@ -14,40 +14,39 @@
...
 public interface ISpellIngredient {
-    /**
-     * The codec used to serialize and deserialize any ingredient.
-     */
     Codec<ISpellIngredient> CODEC = ResourceLocation.CODEC.dispatch("type", ISpellIngredient::getType, ArsMagicaAPI.get().getSpellDataManager()::getSpellIngredientCodec);
-
-    /**
-     * The codec used to serialize and deserialize any ingredient in a network context.
-     */
     Codec<ISpellIngredient> NETWORK_CODEC = ResourceLocation.CODEC.dispatch("type", ISpellIngredient::getType, ArsMagicaAPI.get().getSpellDataManager()::getSpellIngredientNetworkCodec);
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/spell/ISpellIngredient.java:18]: Why remove the comments from the public constants?

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/spell/ISpellPart.java [hunk 27]
```diff
@@ -3,18 +3,16 @@
 import net.minecraftforge.registries.IForgeRegistryEntry;
 
 /**
- * Base interface for a spell part. A spell part can be a component ({@link ISpellComponent}), a modifier ({@link ISpellModifier}) or a shape ({@link ISpellShape})
+ * Base interface for a spell part. A spell part can be a component, a modifier or a shape.
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/spell/ISpellPart.java]: Why remove the links to the respective interfaces?

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/spell/ISpellPartStatModifier.java [hunk 28]
```diff
@@ -2,20 +2,21 @@
...
-     * @return the new modified value
+     * @param base     The base value being modified.
+     * @param modified The value with all previous modifications.
+     * @param spell    The spell this is calculated for.
+     * @param caster   The entity casting the spell.
+     * @param target   The target of the spell.
+     * @return The modified value.
      */
-    float modify(float base, float modified, ISpell spell, LivingEntity caster, @Nullable HitResult target);
+    float modify(float base, float modified, ISpell spell, LivingEntity caster, HitResult target);
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/spell/ISpellPartStatModifier.java]: Why remove the @Nullable if the parameter is nullable?

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/util/IDataManager.java [hunk 29]
```diff
@@ -11,26 +10,20 @@
...
     /**
-     * Get the value for the id or null.
-     *
-     * @param id the id of the requested value
-     * @return the requested value or null if it is not loaded
+     * @param id The id of the requested value.
+     * @return An optional of the requested value, or null if it is not loaded.
      */
-    @Nullable T getNullable(ResourceLocation id);
+    T getNullable(ResourceLocation id);
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/util/IDataManager.java]: Why remove the `@Nullable` from a nullable method in a package that is `@MethodsReturnNonNullByDefault`?

File: src/data/java/com/github/minecraftschurlimods/arsmagicalegacy/data/AMBlockStateProvider.java [hunk 30]
```diff
@@ -37,7 +37,6 @@
 
 import static com.github.minecraftschurlimods.arsmagicalegacy.common.init.AMBlocks.*;
 
-@SuppressWarnings({"ConstantConditions", "SameParameterValue"})
```
Comment (Minecraftschurli) [inline src/data/java/com/github/minecraftschurlimods/arsmagicalegacy/data/AMBlockStateProvider.java]: Leave in the warning suppression

**Review by Minecraftschurli — CHANGES_REQUESTED** [review]
Review the first 68 files... Changes required!

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/ArsMagicaLegacyCommand.java [hunk 31]
```diff
@@ -0,0 +1,691 @@
...
+    public static final String SKILL_POINT_ADD_MULTIPLE = "commands." + ArsMagicaAPI.MOD_ID + ".skill_point.add.multiple.success";
+    public static final String SKILL_POINT_ADD_SINGLE = "commands." + ArsMagicaAPI.MOD_ID + ".skill_point.add.single.success";
+    public static final String SKILL_POINT_CONSUME_MULTIPLE = "commands." + ArsMagicaAPI.MOD_ID + ".skill_point.consume.multiple.success";
+    public static final String SKILL_POINT_CONSUME_SINGLE = "commands." + ArsMagicaAPI.MOD_ID + ".skill_point.consume.single.success";
+    public static final String SKILL_POINT_GET = "commands." + ArsMagicaAPI.MOD_ID + ".skill_point.get.success";
+    public static final String SKILL_POINT_SET_MULTIPLE = "commands." + ArsMagicaAPI.MOD_ID + ".skill_point.set.multiple.success";
+    public static final String SKILL_POINT_SET_SINGLE = "commands." + ArsMagicaAPI.MOD_ID + ".skill_point.set.single.success";
+    public static final String SKILL_POINT_UNKNOWN = "commands." + ArsMagicaAPI.MOD_ID + ".skill_point.unknown";
+    public static final String SKILL_UNKNOWN = "commands." + ArsMagicaAPI.MOD_ID + ".skill.unknown";
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/ArsMagicaLegacyCommand.java]: Move to an interface

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/ArsMagicaLegacyCommand.java [hunk 32]
```diff
@@ -0,0 +1,691 @@
...
+                        .then(Commands.literal("get")
+                                .then(Commands.argument("target", EntityArgument.players())
+                                        .then(Commands.argument("skill_point", ResourceLocationArgument.id())
+                                                .suggests(SUGGEST_SKILL_POINTS)
+                                                .executes(ArsMagicaLegacyCommand::getSkillPoint)))
+                                .then(Commands.argument("skill_point", ResourceLocationArgument.id())
+                                        .suggests(SUGGEST_SKILL_POINTS)
+                                        .executes(ArsMagicaLegacyCommand::getSkillPointSelf))))
+        );
+    }
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/ArsMagicaLegacyCommand.java]: Move each command to its own class like Skill command was before

**Review by Minecraftschurli — CHANGES_REQUESTED** [review]
Review changes to the commands

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/ArsMagicaAPI.java (hunk 2 above)
Comment (IchHabeHunger54) [reply src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/ArsMagicaAPI.java:173]: final is useless with private (IntelliJ suggestion)
I removed @SuppressWarnings everywhere

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/client/OcculusTabRenderer.java (hunk 5 above)
Comment (IchHabeHunger54) [reply src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/client/OcculusTabRenderer.java:22]: It does.

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/AltarStructureMaterialProvider.java (hunk 6 above)
Comment (IchHabeHunger54) [reply src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/AltarStructureMaterialProvider.java]: Why? Our vanilla providers don't do that either

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/etherium/EtheriumType.java (hunk 16 above)
Comment (IchHabeHunger54) [reply src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/etherium/EtheriumType.java:11]: Yes they are.

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/event/SpellEvent.java (hunk 17 above)
Comment (IchHabeHunger54) [reply src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/event/SpellEvent.java:20]: Because the entity isn't nullable, it is always the entity using the item

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/spell/ISpellPartStatModifier.java (hunk 28 above)
Comment (IchHabeHunger54) [reply src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/spell/ISpellPartStatModifier.java]: Readded it.

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/util/IDataManager.java (hunk 29 above)
Comment (IchHabeHunger54) [reply src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/util/IDataManager.java]: Readded it.

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/spell/ISpellIngredient.java (hunk 26 above)
Comment (IchHabeHunger54) [reply src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/spell/ISpellIngredient.java:18]: Because the usage is obvious, and we have a vast amount of network codecs that all don't have a comment (consistency!!1)

File: src/data/java/com/github/minecraftschurlimods/arsmagicalegacy/data/AMBlockStateProvider.java (hunk 30 above)
Comment (IchHabeHunger54) [reply src/data/java/com/github/minecraftschurlimods/arsmagicalegacy/data/AMBlockStateProvider.java]: Ok.

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/ArsMagicaLegacyCommand.java (hunk 32 above)
Comment (IchHabeHunger54) [reply src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/ArsMagicaLegacyCommand.java]: I can move them to their own class, yes, but I'd still keep them as one command (that's how similar mods, like Astral Sorcery, Minecolonies etc. do it as well)

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/AltarStructureMaterialProvider.java (hunk 6 above)
Comment (Minecraftschurli) [reply src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/AltarStructureMaterialProvider.java]: that is the point it is not our provider it is our api for other providers vanilla/forge has them abstract

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/ArsMagicaAPI.java (hunk 2 above)
Comment (Minecraftschurli) [reply src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/ArsMagicaAPI.java:173]: > I removed @SuppressWarnings everywhere

Leave them in

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/ArsMagicaLegacyCommandTranslations.java [hunk 33]
```diff
@@ -0,0 +1,45 @@
+package com.github.minecraftschurlimods.arsmagicalegacy.server.commands;
+
+import com.github.minecraftschurlimods.arsmagicalegacy.api.ArsMagicaAPI;
+import org.jetbrains.annotations.ApiStatus.NonExtendable;
+
+@NonExtendable
+public interface ArsMagicaLegacyCommandTranslations {
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/ArsMagicaLegacyCommandTranslations.java]: Rename to `CommandTranslations` since it is internal anyway (too long)

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/ArsMagicaLegacyCommand.java [hunk 34]
```diff
@@ -0,0 +1,50 @@
...
+import java.util.Optional;
+import java.util.concurrent.CompletableFuture;
+import java.util.function.BiConsumer;
+import java.util.stream.Stream;
+
+import static com.github.minecraftschurlimods.arsmagicalegacy.server.commands.ArsMagicaLegacyCommandTranslations.*;
+
+public class ArsMagicaLegacyCommand {
+    public static void register(CommandDispatcher<CommandSourceStack> dispatcher) {
+        LiteralArgumentBuilder<CommandSourceStack> builder = Commands.literal(ArsMagicaAPI.MOD_ID).requires(p -> p.hasPermission(2));
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/ArsMagicaLegacyCommand.java]: move to the permission system with nodes for each command/subcommand

File: src/main/resources/META-INF/mods.toml [hunk 35]
```diff
@@ -16,37 +16,37 @@ description = '''
...
+modId = "minecraft"
+mandatory = true
+versionRange = "${mc_version_range}"
+ordering = "NONE"
+side = "BOTH"
 
-[modproperties.${mod_id}]
-    catalogueItemIcon="${mod_id}:occulus"
+[modproperties.${ mod_id }]
+catalogueItemIcon = "${mod_id}:occulus"
```
Comment (Minecraftschurli) [inline src/main/resources/META-INF/mods.toml]: This format change breaks the modproperties block (I tested it before)

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/SkillSubcommand.java [hunk 36]
```diff
@@ -0,0 +1,227 @@
...
+    }
+
+    private static CompletableFuture<Suggestions> suggestSkills(CommandContext<CommandSourceStack> context, SuggestionsBuilder builder) {
+        return SharedSuggestionProvider.suggestResource(ArsMagicaAPI.get().getSkillManager().getSkills().stream().map(ISkill::getId), builder);
+    }
+
+    private static Component createSkillListComponent(Stream<ISkill> stream) {
+        return stream.map(ITranslatable::getDisplayName).reduce((component, component2) -> component.copy().append("\n").append(component2)).orElse(new TranslatableComponent(""));
+    }
+}
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/SkillSubcommand.java]: Use the code from SkillCommand here instead and rename all *Subcommand to *Command and move logic from ArsMagicaLegacyCommand to AMCommands

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/AffinitySubcommand.java [hunk 37]
```diff
@@ -0,0 +1,126 @@
...
+
+import static com.github.minecraftschurlimods.arsmagicalegacy.server.commands.ArsMagicaLegacyCommandTranslations.*;
+
+public class AffinitySubcommand {
+    private static final SuggestionProvider<CommandSourceStack> SUGGEST_AFFINITIES = AffinitySubcommand::suggestAffinities;
+    private static final DynamicCommandExceptionType ERROR_UNKNOWN_AFFINITY = new DynamicCommandExceptionType(message -> new TranslatableComponent(AFFINITY_UNKNOWN, message));
+    
+    public static void register(LiteralArgumentBuilder<CommandSourceStack> builder) {
+        builder.then(Commands.literal("affinity")
+                .then(Commands.literal("set")
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/AffinitySubcommand.java]: Maybe add an add subcommand

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/ResetSubcommand.java [hunk 38]
```diff
@@ -0,0 +1,62 @@
...
+import net.minecraft.server.level.ServerPlayer;
+
+import java.util.Collection;
+import java.util.List;
+
+import static com.github.minecraftschurlimods.arsmagicalegacy.server.commands.ArsMagicaLegacyCommandTranslations.*;
+
+public class ResetSubcommand {
+    public static void register(LiteralArgumentBuilder<CommandSourceStack> builder) {
+        builder.then(Commands.literal("reset")
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/ResetSubcommand.java]: I don't really like this command

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/SkillPointSubcommand.java [hunk 39]
```diff
@@ -0,0 +1,186 @@
...
+
+import static com.github.minecraftschurlimods.arsmagicalegacy.server.commands.ArsMagicaLegacyCommandTranslations.*;
+
+public class SkillPointSubcommand {
+    private static final SuggestionProvider<CommandSourceStack> SUGGEST_SKILL_POINTS = SkillPointSubcommand::suggestSkillPoints;
+    private static final DynamicCommandExceptionType ERROR_UNKNOWN_SKILL_POINT = new DynamicCommandExceptionType(message -> new TranslatableComponent(SKILL_POINT_UNKNOWN, message));
+
+    public static void register(LiteralArgumentBuilder<CommandSourceStack> builder) {
+        builder.then(Commands.literal("skill_point")
+                .then(Commands.literal("add")
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/SkillPointSubcommand.java]: Maybe add a clear subcommand

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/network/BEClientSyncPacket.java [hunk 40]
```diff
@@ -22,8 +21,8 @@ public BEClientSyncPacket(FriendlyByteBuf buf) {
 
     @Override
     public void serialize(FriendlyByteBuf buf) {
-        buf.writeBlockPos(this.pos);
-        buf.writeNbt(this.tag);
+        buf.writeBlockPos(pos);
+        buf.writeNbt(tag);
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/network/BEClientSyncPacket.java:25]: `this.`

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/network/LearnSkillPacket.java [hunk 41]
```diff
@@ -20,8 +19,8 @@ public void serialize(FriendlyByteBuf buf) {
 
     @Override
     public void handle(NetworkEvent.Context ctx) {
-        ArsMagicaAPI.IArsMagicaAPI api = ArsMagicaAPI.get();
-        ISkillHelper skillHelper = api.getSkillHelper();
+        var api = ArsMagicaAPI.get();
+        var skillHelper = api.getSkillHelper();
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/network/LearnSkillPacket.java:23]: Please don't replace explicit class with var

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/compat/patchouli/CapStateMatcher.java [hunk 42]
```diff
@@ -13,7 +13,7 @@
     private final TriPredicate<BlockGetter, BlockPos, BlockState> predicate;
 
     CapStateMatcher() {
-        this.predicate = (blockGetter, blockPos, state) -> AltarMaterialManager.instance().getCapMaterial(state.getBlock()).map(AltarCapMaterial::cap).filter(state::is).isPresent();
+        predicate = (blockGetter, blockPos, state) -> AltarMaterialManager.instance().getCapMaterial(state.getBlock()).map(AltarCapMaterial::cap).filter(state::is).isPresent();
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/compat/patchouli/CapStateMatcher.java]: `this.`

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/compat/patchouli/MainBlockStateMatcher.java [hunk 43]
```diff
@@ -13,7 +13,7 @@
     private final TriPredicate<BlockGetter, BlockPos, BlockState> predicate;
 
     MainBlockStateMatcher() {
-        this.predicate = (blockGetter, blockPos, state) -> AltarMaterialManager.instance().getStructureMaterial(state.getBlock()).map(AltarStructureMaterial::block).filter(state::is).isPresent();
+        predicate = (blockGetter, blockPos, state) -> AltarMaterialManager.instance().getStructureMaterial(state.getBlock()).map(AltarStructureMaterial::block).filter(state::is).isPresent();
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/compat/patchouli/MainBlockStateMatcher.java]: `this.`

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/compat/patchouli/SpellPartPage.java [hunk 44]
```diff
@@ -29,28 +29,28 @@
     public void build(int x, int y, int page) {
         this.x = x;
         this.y = y;
-        this._part = ArsMagicaAPI.get().getSpellPartRegistry().getValue(ResourceLocation.tryParse(part));
+        _part = ArsMagicaAPI.get().getSpellPartRegistry().getValue(ResourceLocation.tryParse(part));
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/compat/patchouli/SpellPartPage.java]: `this.`

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/compat/patchouli/SpellPartPage.java [hunk 45]
```diff
@@ -29,28 +29,28 @@
...
+//        RenderUtil.drawTexturedModalRectClassic(x, y, 112, 175, 60, 40, 40, 40, context.getGui().getBlitOffset());
+//        context.getGui().setBlitOffset(context.getGui().getBlitOffset() - 1);
+//        RenderSystem.disableBlend();
+//        List<ISpellModifier> modifiers = cacheModifiers();
+//        if (modifiers.isEmpty()) cy -= 16;
+//        else cy += ((modifiers.size() / 7) * 16) + 8;
         renderRecipe(poseStack, context, cx, cy, mouseX, mouseY);
         RenderSystem.enableBlend();
-        ISkill skill = ArsMagicaAPI.get().getSkillManager().get(this._part.getRegistryName());
+        ISkill skill = ArsMagicaAPI.get().getSkillManager().get(_part.getRegistryName());
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/compat/patchouli/SpellPartPage.java]: `this.`

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/compat/patchouli/StairBlockStateMatcher.java [hunk 46]
```diff
@@ -13,14 +13,14 @@
...
-    private final Half                                            half;
+    private final Direction direction;
+    private final Half half;
     private final TriPredicate<BlockGetter, BlockPos, BlockState> predicate;
 
     public StairBlockStateMatcher(Direction direction, Half half) {
         this.direction = direction;
         this.half = half;
-        this.predicate = (blockGetter, blockPos, state) -> AltarMaterialManager.instance().getStructureMaterial(state.getBlock()).map(AltarStructureMaterial::stair).filter(state::is).isPresent() && state.getValue(StairBlock.FACING) == this.direction && state.getValue(StairBlock.HALF) == this.half;
+        predicate = (blockGetter, blockPos, state) -> AltarMaterialManager.instance().getStructureMaterial(state.getBlock()).map(AltarStructureMaterial::stair).filter(state::is).isPresent() && state.getValue(StairBlock.FACING) == direction && state.getValue(StairBlock.HALF) == half;
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/compat/patchouli/StairBlockStateMatcher.java]: `this.`

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/compat/curios/CurioCompat.java [hunk 47]
```diff
@@ -23,6 +22,7 @@
 
 import java.util.UUID;
 import java.util.function.BiFunction;
+import javax.annotation.Nonnull;
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/compat/curios/CurioCompat.java]: Use the jetbrains annotations!

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/EventHandler.java [hunk 48]
```diff
@@ -158,8 +163,17 @@ private static void registerFeature(RegistryEvent.Register<Feature<?>> event) {
...
+        BrewingRecipeRegistry.addRecipe(new AMBrewingRecipe(Potions.AWKWARD, Ingredient.of(AMItems.WAKEBLOOM.get()), AMMobEffects.STANDARD_MANA.get()));
+        BrewingRecipeRegistry.addRecipe(new AMBrewingRecipe(Potions.AWKWARD, Ingredient.of(AMItems.VINTEUM_DUST.get()), AMMobEffects.GREATER_MANA.get()));
+        BrewingRecipeRegistry.addRecipe(new AMBrewingRecipe(Potions.AWKWARD, Ingredient.of(AMItems.ARCANE_ASH.get()), AMMobEffects.EPIC_MANA.get()));
+        BrewingRecipeRegistry.addRecipe(new AMBrewingRecipe(Potions.AWKWARD, Ingredient.of(AMItems.PURIFIED_VINTEUM_DUST.get()), AMMobEffects.LEGENDARY_MANA.get()));
+        BrewingRecipeRegistry.addRecipe(new AMBrewingRecipe(Potions.AWKWARD, Ingredient.of(AMItems.TARMA_ROOT.get()), AMMobEffects.INFUSED_MANA.get()));
+    }
+
     public static void registerSpellIngredientTypes() {
-        ISpellDataManager spellDataManager = ArsMagicaAPI.get().getSpellDataManager();
+        var spellDataManager = ArsMagicaAPI.get().getSpellDataManager();
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/EventHandler.java:181]: Don't replace explicit type with var

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/EventHandler.java [hunk 49]
```diff
@@ -247,26 +260,31 @@ private static void playerClone(PlayerEvent.Clone event) {
     private static void playerItemPickup(PlayerEvent.ItemPickupEvent event) {
         if (event.getPlayer().isCreative()) return;
         if (event.getPlayer().isSpectator()) return;
-        if (ArsMagicaAPI.get().getMagicHelper().knowsMagic(event.getPlayer())) return;
-        if (!ItemStack.isSameItemSameTags(ArsMagicaAPI.get().getBookStack(), event.getStack())) return;
-        ArsMagicaAPI.get().getMagicHelper().awardXp(event.getPlayer(), 0);
+        var api = ArsMagicaAPI.get();
+        var helper = api.getMagicHelper();
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/EventHandler.java:270]: don't use var here

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/EventHandler.java [hunk 50]
```diff
@@ -247,26 +260,31 @@ private static void playerClone(PlayerEvent.Clone event) {
...
     }
 
     private static void playerItemCrafted(PlayerEvent.ItemCraftedEvent event) {
         if (event.getPlayer().isCreative()) return;
         if (event.getPlayer().isSpectator()) return;
-        if (ArsMagicaAPI.get().getMagicHelper().knowsMagic(event.getPlayer())) return;
-        if (!ItemStack.isSameItemSameTags(ArsMagicaAPI.get().getBookStack(), event.getCrafting())) return;
-        ArsMagicaAPI.get().getMagicHelper().awardXp(event.getPlayer(), 0);
+        var api = ArsMagicaAPI.get();
+        var helper = api.getMagicHelper();
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/EventHandler.java:280]: don't use var here

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/EventHandler.java [hunk 51]
```diff
@@ -247,26 +260,31 @@ private static void playerClone(PlayerEvent.Clone event) {
...
     }
 
     private static void playerTick(TickEvent.PlayerTickEvent event) {
         if (event.side != LogicalSide.SERVER) return;
         if (event.phase != TickEvent.Phase.START) return;
         Player player = event.player;
         if (player.isDeadOrDying() || !player.getCapability(ManaHelper.getManaCapability()).isPresent()) return;
-        ArsMagicaAPI.get().getManaHelper().increaseMana(player, (float) player.getAttributeValue(AMAttributes.MANA_REGEN.get()));
-        ArsMagicaAPI.get().getBurnoutHelper().decreaseBurnout(player, (float) player.getAttributeValue(AMAttributes.BURNOUT_REGEN.get()));
+        var api = ArsMagicaAPI.get();
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/EventHandler.java:291]: don't use var here

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/EventHandler.java [hunk 52]
```diff
@@ -357,14 +375,15 @@ private static void addReloadListener(AddReloadListenerEvent event) {
     private static void playerLevelUp(PlayerLevelUpEvent event) {
         Player player = event.getPlayer();
         int level = event.getLevel();
-        ArsMagicaAPI.IArsMagicaAPI api = ArsMagicaAPI.get();
+        var api = ArsMagicaAPI.get();
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/EventHandler.java:384]: don't replace explicit type with var

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/EventHandler.java [hunk 53]
```diff
@@ -381,21 +400,21 @@ private static void playerLevelUp(PlayerLevelUpEvent event) {
...
-        event.getPlayer().getLevel().playSound(null, event.getPlayer().getX(), event.getPlayer().getY(), event.getPlayer().getZ(), AMSounds.MAGIC_LEVEL_UP.get(), SoundSource.MASTER, 1f, 1f);
+        event.getPlayer().getLevel().playSound(null, event.getPlayer().getX(), event.getPlayer().getY(), event.getPlayer().getZ(), AMSounds.MAGIC_LEVEL_UP.get(), SoundSource.PLAYERS, 1f, 1f);
     }
 
     private static void manaCostPre(SpellEvent.ManaCost.Pre event) {
         LivingEntity caster = event.getEntityLiving();
         float cost = event.getBase();
         if (caster instanceof Player player) {
-            ISpellDataManager iSpellDataManager = ArsMagicaAPI.get().getSpellDataManager();
+            var api = ArsMagicaAPI.get();
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/EventHandler.java:416]: don't use var here

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/ClientInit.java [hunk 54]
```diff
@@ -128,15 +128,16 @@ private static void modelRegister(ModelRegistryEvent event) {
         for (Item item : ForgeRegistries.ITEMS) {
             ResourceLocation itemId = item.getRegistryName();
             if (itemId == null) continue;
+            var api = ArsMagicaAPI.get();
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/ClientInit.java:134]: don't use var here

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/SkillIconAtlas.java [hunk 55]
```diff
@@ -51,7 +47,7 @@ public TextureAtlasSprite getSprite(@Nullable ResourceLocation location) {
     protected TextureAtlas.Preparations prepare(ResourceManager resourceManager, ProfilerFiller pProfiler) {
         int pathLength = ("textures/" + PREFIX + "/").length();
         int suffixLength = SUFFIX.length();
-        this.resourceLocations = resourceManager.listResources("textures/" + PREFIX, RESOURCE_PREDICATE).stream().map(resourceLocation -> {
+        resourceLocations = resourceManager.listResources("textures/" + PREFIX, RESOURCE_PREDICATE).stream().map(resourceLocation -> {
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/SkillIconAtlas.java]: `this.`

**Review by Minecraftschurli — CHANGES_REQUESTED** [review]
Another review after these changes it should be good. 
But this is a big PR so I would like a second pair of eyes to have a look.

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/ArsMagicaAPI.java [hunk 56]
```diff
@@ -50,162 +47,129 @@ private ArsMagicaAPI() {
...
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/ArsMagicaAPI.java:173]: Re add the @SuppressWarnings then I can approve this PR

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/AltarStructureMaterialProvider.java (hunk 6 above)
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/AltarStructureMaterialProvider.java]: either leave the namespace in the string or don't implement the method here

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/ObeliskFuelProvider.java (hunk 9 above)
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/ObeliskFuelProvider.java]: here too

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/PrefabSpellProvider.java [hunk 57]
```diff
@@ -0,0 +1,118 @@
...
+        for (Map.Entry<ResourceLocation, JsonObject> entry : data.entrySet()) {
+            ResourceLocation id = entry.getKey();
+            JsonObject spell = entry.getValue();
+            DataProvider.save(GSON, pCache, spell, generator.getOutputFolder().resolve("data/" + id.getNamespace() + "/prefab_spells/" + id.getPath() + ".json"));
+        }
+    }
+
+    @Override
+    public String getName() {
+        return "Prefab Spells";
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/PrefabSpellProvider.java]: here too

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/SkillProvider.java (hunk 14 above)
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/SkillProvider.java]: here too

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/SpellPartDataProvider.java (hunk 15 above)
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/data/SpellPartDataProvider.java]: here too

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/magic/IManaHelper.java [hunk 58]
```diff
@@ -7,50 +7,49 @@
...
+
     /**
      * Sets the mana value of the given entity.
      *
-     * @param livingEntity the entity to set the mana value for
+     * @param entity The entity to set the mana value for.
+     * @param amount The amount to set the mana value to.
      */
-    void setMana(LivingEntity livingEntity, float amount);
+    void setMana(LivingEntity entity, float amount);
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/magic/IManaHelper.java]: why is the burnout counterpart a boolean and this not?

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/spell/ISpellPart.java [hunk 59]
```diff
@@ -3,18 +3,16 @@
 import net.minecraftforge.registries.IForgeRegistryEntry;
 
 /**
- * Base interface for a spell part. A spell part can be a component ({@link ISpellComponent}), a modifier ({@link ISpellModifier}) or a shape ({@link ISpellShape})
+ * Base interface for a spell part. A spell part can be an {@link ISpellComponent}, an {@link ISpellModifier} or an {@link ISpellShape}.
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/spell/ISpellPart.java]:
```suggestion
 * Base interface for a spell part. A spell part can be a component of type {@link ISpellComponent}, a modifier of type {@link ISpellModifier} or a shape of type {@link ISpellShape}.
```

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/spell/ISpellPartStatModifier.java [hunk 60]
```diff
@@ -2,20 +2,23 @@
 
 import net.minecraft.world.entity.LivingEntity;
 import net.minecraft.world.phys.HitResult;
-import org.jetbrains.annotations.Nullable;
+
+import javax.annotation.Nullable;
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/spell/ISpellPartStatModifier.java]: always use the jetbrains annotations

File: src/data/java/com/github/minecraftschurlimods/arsmagicalegacy/data/AMSoundDefinitionsProvider.java [hunk 61]
```diff
@@ -0,0 +1,54 @@
...
+        ResourceLocation location = supplier.getId();
+        if (this.sounds.contains(location)) return;
+        this.sounds.add(location);
+        String subtitle = "subtitle." + location.getNamespace() + "." + location.getPath();
+        String sound = location.toString().replace('.', '/');
+        if (sounds == 1) {
+            add(supplier, definition().with(sound(sound)).subtitle(subtitle));
+        } else {
+            SoundDefinition def = definition();
+            for (int value = 1; value < sounds - 1; value++) {
```
Comment (Minecraftschurli) [inline src/data/java/com/github/minecraftschurlimods/arsmagicalegacy/data/AMSoundDefinitionsProvider.java]: shouldn't it be +1 not -1
```suggestion
            for (int value = 1; value < sounds + 1; value++) {
```

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/DistProxy.java [hunk 62]
```diff
@@ -1,8 +1,5 @@
 package com.github.minecraftschurlimods.arsmagicalegacy.client;
 
-/**
- * Ugly hack to prevent unwanted classloading.
- */
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/DistProxy.java:5]: Why remove a doc comment? please don't make the code less documented

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/gui/ColorUtil.java [hunk 63]
```diff
@@ -10,35 +10,19 @@
...
-     * @return the red value (from 0.0 to 1.0)
-     */
     public static float getRed(int color) {
         return (0xFF & (color >> 16)) / 255f;
     }
 
-    /**
-     * @param rgbColor an RGB color value
-     * @return the corresponding HSB value
-     */
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/gui/ColorUtil.java]: again why make it less documented

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/gui/RuneBagScreen.java [hunk 64]
```diff
@@ -10,16 +10,12 @@
 import net.minecraft.world.entity.player.Inventory;
 
 /**
- * Mostly taken from McJty's tutorials and the Botania mod.
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/gui/RuneBagScreen.java]: Why remove the attribution?

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/gui/dropdis/DragPane.java [hunk 65]
```diff
@@ -8,10 +8,10 @@
 import net.minecraft.client.gui.components.events.GuiEventListener;
 import net.minecraft.client.gui.narration.NarratableEntry;
 import net.minecraft.client.gui.narration.NarrationElementOutput;
-import org.jetbrains.annotations.Nullable;
 
 import java.util.ArrayList;
 import java.util.List;
+import javax.annotation.Nullable;
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/gui/dropdis/DragPane.java]: always use the jetbrains annotations

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/gui/dropdis/Draggable.java [hunk 66]
```diff
@@ -38,12 +38,12 @@ public Draggable(int x, int y, int width, int height, TextureAtlasSprite sprite,
...
-            this.dragOffsetX = mouseX - this.x;
-            this.dragOffsetY = mouseY - this.y;
+            dragOffsetX = mouseX - x;
+            dragOffsetY = mouseY - y;
             dragOffsetSet = true;
         }
-        this.x = (int)(mouseX - this.dragOffsetX);
-        this.y = (int)(mouseY - this.dragOffsetY);
+        x = (int) (mouseX - dragOffsetX);
+        y = (int) (mouseY - dragOffsetY);
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/gui/dropdis/Draggable.java]: leave the `this.`

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/gui/dropdis/DropArea.java [hunk 67]
```diff
@@ -8,6 +8,24 @@
...
+
+    static void vLine(PoseStack poseStack, int x, int minY, int maxY, int color) {
+        if (maxY < minY) {
+            int i = minY;
+            minY = maxY;
+            maxY = i;
+        }
+        GuiComponent.fill(poseStack, x, minY + 1, x + 1, maxY, color);
+    }
+
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/gui/dropdis/DropArea.java]: static methods in interfaces go at the bottom not the top

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/gui/occulus/OcculusScreen.java [hunk 68]
```diff
@@ -28,9 +28,6 @@
     private Button nextPage;
     private OcculusTabRenderer activeTab;
 
-    /**
-     * Creates the occulus screen. Sets the correct size and sets the first tab as the active one.
-     */
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/gui/occulus/OcculusScreen.java:33]: why make code less documented

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/model/AltarCoreModel.java [hunk 69]
```diff
@@ -10,20 +10,19 @@
 import net.minecraftforge.client.model.BakedModelWrapper;
 import net.minecraftforge.client.model.data.EmptyModelData;
 import net.minecraftforge.client.model.data.IModelData;
-import org.jetbrains.annotations.NotNull;
 import org.jetbrains.annotations.Nullable;
 
 import java.util.ArrayList;
 import java.util.List;
 import java.util.Random;
+import javax.annotation.Nonnull;
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/model/AltarCoreModel.java]: always use the jetbrains annotations

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/model/SpellRuneModel.java [hunk 70]
```diff
@@ -10,18 +10,18 @@
 import net.minecraft.world.level.block.state.BlockState;
 import net.minecraftforge.client.model.BakedModelWrapper;
 import net.minecraftforge.client.model.data.IModelData;
-import org.jetbrains.annotations.NotNull;
 import org.jetbrains.annotations.Nullable;
 
 import java.util.List;
 import java.util.Random;
+import javax.annotation.Nonnull;
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/model/SpellRuneModel.java]: always use jetbrains annotations

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/WakebloomBlock.java [hunk 71]
```diff
@@ -21,9 +21,6 @@ public boolean canSurvive(BlockState state, LevelReader level, BlockPos pos) {
         return level.getBlockState(pos.below()).getBlock() == Blocks.WATER;
     }
 
-    /**
-     * {@see net.minecraft.world.level.block.WaterlilyBlock#mayPlaceOn(BlockState, BlockGetter, BlockPos)}
-     */
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/WakebloomBlock.java:26]: why make code less documented

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/altar/AltarCoreBlock.java [hunk 72]
```diff
@@ -33,8 +32,6 @@ protected void createBlockStateDefinition(StateDefinition.Builder<Block, BlockSt
         pBuilder.add(FORMED);
     }
 
-    @SuppressWarnings("unchecked")
-    @Nullable
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/altar/AltarCoreBlock.java]: Why? it contains a cast that is "unchecked" but safe so the suppreession is correct and it is nullable in a package that has methods return nonnull by default

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/altar/AltarCoreBlockEntity.java [hunk 73]
```diff
@@ -56,217 +57,176 @@
...
+    public static final String PROVIDERS_KEY = ArsMagicaAPI.MOD_ID + ":bound_providers";
+    public static final String RECIPE_KEY = ArsMagicaAPI.MOD_ID + ":recipe";
+    public static final String CAMO_KEY = ArsMagicaAPI.MOD_ID + ":camo";
+    public static final String ALTAR_POWER_KEY = ArsMagicaAPI.MOD_ID + ":altar_power_key";
     public static final String REQUIRED_POWER_KEY = ArsMagicaAPI.MOD_ID + ":required_power_key";
-
     private final ModelDataMap modelData = new ModelDataMap.Builder().withProperty(CAMO_STATE).build();
-
-    @Nullable private AltarStructureMaterial structureMaterial;
-    @Nullable private AltarCapMaterial       capMaterial;
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/altar/AltarCoreBlockEntity.java:80]: why remove the nullability? it is nullable

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/altar/AltarCoreBlockEntity.java [hunk 74]
```diff
@@ -56,217 +57,176 @@
...
-
-    private int     requiredPower = 0;
-    private boolean isCrafting;
-    private int     powerLevel = -1;
-    public  int     checkCounter;
-
-    @Nullable private BlockPos  lecternPos;
-    @Nullable private BlockPos  leverPos;
-    @Nullable private BlockPos  viewPos;
-    @Nullable private Direction direction;
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/altar/AltarCoreBlockEntity.java:159]: again why remove nullability?

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/altar/AltarCoreBlockEntity.java [hunk 75]
```diff
@@ -56,217 +57,176 @@
...
 import java.util.HashSet;
 import java.util.List;
-import java.util.Map;
 import java.util.Optional;
 import java.util.Queue;
 import java.util.Set;
 import java.util.function.Function;
 import java.util.function.Predicate;
 import java.util.stream.Collectors;
+import javax.annotation.Nonnull;
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/altar/AltarCoreBlockEntity.java]: use jetbrains annotations

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/blackaurem/BlackAuremBlockEntity.java [hunk 76]
```diff
@@ -20,23 +20,26 @@
 import net.minecraft.world.phys.Vec3;
 import net.minecraftforge.common.capabilities.Capability;
 import net.minecraftforge.common.util.LazyOptional;
-import org.jetbrains.annotations.NotNull;
 import org.jetbrains.annotations.Nullable;
 
 import java.util.Comparator;
 import java.util.List;
+import javax.annotation.Nonnull;
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/blackaurem/BlackAuremBlockEntity.java]: use jetbrains annotations

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/celestialprism/CelestialPrismBlockEntity.java [hunk 77]
```diff
@@ -14,20 +14,24 @@
 import net.minecraft.world.level.block.state.BlockState;
 import net.minecraftforge.common.capabilities.Capability;
 import net.minecraftforge.common.util.LazyOptional;
-import org.jetbrains.annotations.NotNull;
 import org.jetbrains.annotations.Nullable;
 
+import javax.annotation.Nonnull;
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/celestialprism/CelestialPrismBlockEntity.java]: always use jetbrains annotations

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/celestialprism/CelestialPrismBlock.java [hunk 78]
```diff
@@ -53,39 +50,36 @@ public RenderShape getRenderShape(BlockState pState) {
         return RenderShape.MODEL;
     }
 
-    @Nullable
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/celestialprism/CelestialPrismBlock.java:56]: don't remove nullable if it is nullable

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/obelisk/ObeliskBlock.java [hunk 79]
```diff
@@ -30,32 +29,26 @@
...
     }
 
     @Override
-    protected void createBlockStateDefinition(final StateDefinition.Builder<Block, BlockState> builder) {
+    protected void createBlockStateDefinition(StateDefinition.Builder<Block, BlockState> builder) {
         super.createBlockStateDefinition(builder);
         builder.add(PART);
     }
 
-    @Nullable
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/obelisk/ObeliskBlock.java:43]: don't remove nullable if it is nullable

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/obelisk/ObeliskBlock.java [hunk 80]
```diff
@@ -30,32 +29,26 @@
...
     @Override
     public <T extends BlockEntity> BlockEntityTicker<T> getTicker(Level level, BlockState state, BlockEntityType<T> blockEntityType) {
         return level.isClientSide() || state.getValue(PART) != Part.LOWER ? null : createTickerHelper(blockEntityType, AMBlockEntities.OBELISK.get(), (level1, pos, state1, blockEntity) -> blockEntity.tick(level1, pos, state1));
     }
 
-    @Nullable
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/obelisk/ObeliskBlock.java:49]: don't remove nullable if it is nullable

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/obelisk/ObeliskBlockEntity.java [hunk 81]
```diff
@@ -30,9 +30,15 @@
 import org.jetbrains.annotations.Nullable;
 
 import java.util.Optional;
+import javax.annotation.Nonnull;
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/obelisk/ObeliskBlockEntity.java]: always use jetbrains annotations

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/effect/BurnoutReduction.java [hunk 82]
```diff
@@ -1,14 +1,9 @@
...
-import com.github.minecraftschurlimods.arsmagicalegacy.common.init.AMBlocks;
-import com.github.minecraftschurlimods.arsmagicalegacy.common.init.AMItems;
 import net.minecraft.world.effect.MobEffectCategory;
 import net.minecraft.world.entity.ai.attributes.AttributeModifier;
 import net.minecraft.world.entity.ai.attributes.RangedAttribute;
 
-/**
- * This class is required so that it doesn't cause classloading issues in {@link AMBlocks} and {@link AMItems}
- */
 public class BurnoutReduction extends AMMobEffect {
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/effect/BurnoutReduction.java:8]: why does this class create an attribute in the constructor? attributes are to be accessed through the registry!

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/effect/ManaRegenEffect.java [hunk 83]
```diff
@@ -1,14 +1,9 @@
...
-import com.github.minecraftschurlimods.arsmagicalegacy.common.init.AMBlocks;
-import com.github.minecraftschurlimods.arsmagicalegacy.common.init.AMItems;
 import net.minecraft.world.effect.MobEffectCategory;
 import net.minecraft.world.entity.ai.attributes.AttributeModifier;
 import net.minecraft.world.entity.ai.attributes.RangedAttribute;
 
-/**
- * This class is required so that it doesn't cause classloading issues in {@link AMBlocks} and {@link AMItems}
- */
 public class ManaRegenEffect extends AMMobEffect {
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/effect/ManaRegenEffect.java:7]: why does this class create an attribute in the constructor? attributes are to be accessed through the registry!

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/init/AMRegistries.java [hunk 84]
```diff
@@ -45,19 +45,14 @@
...
 
-    DeferredRegister<IAffinity>           AFFINITIES           = DeferredRegister.create(IAffinity.class, ArsMagicaAPI.MOD_ID);
-    Supplier<IForgeRegistry<IAffinity>>   AFFINITY_REGISTRY    = AFFINITIES.makeRegistry("affinity", () -> new RegistryBuilder<IAffinity>().setDefaultKey(new ResourceLocation(ArsMagicaAPI.MOD_ID, "none")));
-
-    DeferredRegister<ISpellPart>          SPELL_PARTS          = DeferredRegister.create(ISpellPart.class, ArsMagicaAPI.MOD_ID);
-    Supplier<IForgeRegistry<ISpellPart>>  SPELL_PART_REGISTRY  = SPELL_PARTS.makeRegistry("spell_part", RegistryBuilder::new);
-
-    /**
-     * @param bus the mods event bus
-     */
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/init/AMRegistries.java]: why make the code less documented

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/item/ColoredRuneItem.java [hunk 85]
```diff
@@ -6,39 +6,21 @@
...
 public class ColoredRuneItem extends Item {
     private static final Map<DyeColor, ColoredRuneItem> ITEM_BY_COLOR = Maps.newEnumMap(DyeColor.class);
     private final DyeColor dyeColor;
 
-    /**
-     * Creates a rune with the given color.
-     *
-     * @param pProperties The item properties.
-     * @param dyeColor    The color of the rune.
-     */
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/item/ColoredRuneItem.java:21]: why make the code less documented?

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/item/ColoredRuneItem.java [hunk 86]
```diff
@@ -6,39 +6,21 @@
...
     public ColoredRuneItem(Properties pProperties, DyeColor dyeColor) {
         super(pProperties);
         this.dyeColor = dyeColor;
         ITEM_BY_COLOR.put(dyeColor, this);
     }
 
-    /**
-     * @return The color of this rune.
-     */
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/item/ColoredRuneItem.java]: why make the code less documented?

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/item/ColoredRuneItem.java [hunk 87]
```diff
@@ -6,39 +6,21 @@
...
-    public DyeColor getDyeColor() {
-        return dyeColor;
-    }
-
-    /**
-     * Gets a rune by color.
-     *
-     * @param pColor The color to get the rune for.
-     * @return The rune for the given color.
-     */
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/item/ColoredRuneItem.java]: why make the code less documented?

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/item/MagitechGogglesItem.java [hunk 88]
```diff
@@ -78,7 +78,6 @@ public MagitechGogglesItem() {
         return ImmutableMultimap.of(AMAttributes.MAGIC_VISION.get(), new AttributeModifier(UUID, "magic_vision", 1, AttributeModifier.Operation.ADDITION));
     }
 
-    @Nullable
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/item/MagitechGogglesItem.java:81]: isn't the super method also nullable?

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/item/runebag/RuneBagContainer.java [hunk 89]
```diff
@@ -7,18 +7,12 @@
 import net.minecraft.world.item.ItemStack;
 
 /**
- * Mostly taken from the Botania mod.
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/item/runebag/RuneBagContainer.java:10]: why remove the attribution?

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/item/runebag/RuneBagItem.java [hunk 90]
```diff
@@ -18,11 +18,11 @@
 import net.minecraftforge.items.IItemHandler;
 import net.minecraftforge.items.wrapper.InvWrapper;
 import net.minecraftforge.network.NetworkHooks;
-import org.jetbrains.annotations.NotNull;
 import org.jetbrains.annotations.Nullable;
 
+import javax.annotation.Nonnull;
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/item/runebag/RuneBagItem.java]: always use jetbrains annotations

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/spell/SpellDataManager.java [hunk 91]
```diff
@@ -28,63 +28,54 @@
...
+    public static SpellDataManager instance() {
+        return INSTANCE.get();
+    }
+
     @Override
     public ISpellPartData getDataForPart(ISpellPart part) {
         return get(part.getRegistryName());
     }
 
-    @SuppressWarnings("unchecked")
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/spell/SpellDataManager.java:47]: please leave the unchecked suppressions in there

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/spell/component/Knockback.java [hunk 92]
```diff
@@ -24,7 +24,6 @@ public SpellCastResult invoke(ISpell spell, LivingEntity caster, Level level, Li
         Entity entity = target.getEntity();
         float velocity = ArsMagicaAPI.get().getSpellHelper().getModifiedStat(1, SpellPartStats.SPEED, modifiers, spell, caster, target);
         Vec3 delta = entity.getDeltaMovement();
-        // TODO ((LivingEntity) entity).knockback(); @IHH
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/spell/component/Knockback.java:27]: this implementation bypasses any knockback protection 
What about the method LivingEntity#knockback?

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/spell/component/Repel.java [hunk 93]
```diff
@@ -15,42 +15,37 @@
 import net.minecraft.world.phys.Vec3;
 
 import java.util.List;
+import javax.annotation.Nullable;
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/spell/component/Repel.java]: always use jetbrains annotations

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/util/AMUtil.java [hunk 94]
```diff
@@ -17,68 +17,31 @@
...
-import java.util.function.Predicate;
 import java.util.stream.Collector;
 
 public final class AMUtil {
-    /**
-     * Returns whether the player can anger endermen by looking at them, based on the ender affinity depth.
-     *
-     * @param player The player to check the affinity on
-     * @return Whether the player can anger endermen by looking at them or not
-     */
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/util/AMUtil.java]: why make the code less documented?

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/util/ColoredRegistryObject.java [hunk 95]
```diff
@@ -13,45 +13,20 @@
...
             map.put(color, register.register(color.getName() + "_" + suffix, () -> creator.apply(color)));
         }
     }
 
-    /**
-     * Returns the registry object for the given color.
-     *
-     * @param color The color to get the registry object for.
-     * @return The registry object for the given color.
-     */
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/util/ColoredRegistryObject.java]: why make the code less documented?

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/SkillPointCommand.java [hunk 96]
```diff
@@ -0,0 +1,218 @@
...
+                        .then(Commands.argument("target", EntityArgument.players())
+                                .then(Commands.argument("skill_point", ResourceLocationArgument.id())
+                                        .suggests(SUGGEST_SKILL_POINTS)
+                                        .then(Commands.argument("amount", IntegerArgumentType.integer(0))
+                                                .executes(SkillPointCommand::setSkillPoint))))
+                        .then(Commands.argument("skill_point", ResourceLocationArgument.id())
+                                .suggests(SUGGEST_SKILL_POINTS)
+                                .then(Commands.argument("amount", IntegerArgumentType.integer(0))
+                                        .executes(SkillPointCommand::setSkillPointSelf))))
+                .then(Commands.literal("reset")
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/SkillPointCommand.java]: please rename to clear

**Review by Minecraftschurli — CHANGES_REQUESTED** [review]
There are still a few things left:
- please use the jetbrains annotations
- don't just remove documentation
- don't remove `this.` where possible
- don't remove nullable from nullable things

For the commands I'd suggest using clear instead of reset.

I'd suggest removing the entity stuff from this branch and moving it to the dedicated features/entities branch.

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/gui/dropdis/DropArea.java (hunk 67 above)
Comment (IchHabeHunger54) [reply src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/client/gui/dropdis/DropArea.java]: This is where IntelliJ put them

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/altar/AltarCoreBlock.java (hunk 72 above)
Comment (IchHabeHunger54) [reply src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/altar/AltarCoreBlock.java]: The supermethod already marks it as nullable, hence IJ removed it.
As for the suppression, I removed all suppressions, but I'm gonna readd this one.

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/celestialprism/CelestialPrismBlock.java (hunk 78 above)
Comment (IchHabeHunger54) [reply src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/celestialprism/CelestialPrismBlock.java:56]: Nullability defined in superclass.

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/obelisk/ObeliskBlock.java (hunk 79 above)
Comment (IchHabeHunger54) [reply src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/obelisk/ObeliskBlock.java:43]: Nullability defined in superclass.

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/obelisk/ObeliskBlock.java (hunk 80 above)
Comment (IchHabeHunger54) [reply src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/block/obelisk/ObeliskBlock.java:49]: Nullability defined in superclass.

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/item/MagitechGogglesItem.java (hunk 88 above)
Comment (IchHabeHunger54) [reply src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/item/MagitechGogglesItem.java:81]: Exactly. IntelliJ suggested removing it as the nullability is already defined by the superclass.

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/spell/component/Knockback.java (hunk 92 above)
Comment (IchHabeHunger54) [reply src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/spell/component/Knockback.java:27]: This is the old implementation that allows y-knockback as well.

**Comment by IchHabeHunger54** [comment]
I have previously removed the documentation for the non-api packages and forgot to re-add them; I now did. All public methods, except for overrides, methods marked as internal, constructors, simple getters and setters, and all methods in the entity packages, now have a javadoc in the main sourceset as well.

Additionally, I have unified the suppressions: All unchecked/unsafe, deprecation, and Optional usage warnings are suppressed, while all others are not.

The annotations have been unified too and use Jetbrains where possible.

I did the entity renaming in this PR because this PR is dedicated for cleanup.

This PR should now definitely be merge-ready.

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/event/SpellEvent.java [hunk 97]
```diff
@@ -191,7 +188,7 @@ public void setBurnout(float burnout) {
      * Event to modify the reagents required by the spell.
      */
     public static final class ReagentCost extends SpellEvent {
-        public List<Either<Ingredient, ItemStack>> reagents;
+        public final List<Either<Ingredient, ItemStack>> reagents;
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/event/SpellEvent.java:192]: if you make it final make it mutable in the constructor

**Review by Minecraftschurli — CHANGES_REQUESTED** [review]
Just one little thing

**Review by Minecraftschurli — APPROVED** [review]
:shipit:
