### PR TITLE
Abilities!

### LINKED ISSUE #282: [Crash]: Duplicate id value for 13!
### Describe the bug

[crash-2022-04-25_17.31.13-client.txt](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/files/8558583/crash-2022-04-25_17.31.13-client.txt)

Crash when attempting to create a world.

### Steps to Reproduce

_No response_

### Expected behavior

Smooth world generation

### Screenshots

_No response_

### Version

1.18.2-1.0.1

### Forge Version

40.1.0

### Other Mods

Related.
collective-1.18.2-4.25
alllootdrops_1.18.2-2.4

### Log

```shell
[debug.log](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/files/8558584/debug.log)
```

### LINKED ISSUE #292: Affinity Abilities

### PR DESCRIPTION
**Pull request by IchHabeHunger54**
This PR adds in affinity abilities.

Also includes a version bump to v1.1 and a fix for #282 .

### CODE REVIEW

File: gradle.properties [hunk 1]
```diff
@@ -4,7 +4,7 @@ org.gradle.daemon=false
 mod_group=com.github.minecraftschurli
 mod_id=arsmagicalegacy
 mod_name=Ars Magica: Legacy
-mod_version=1.0.1
+mod_version=1.1
```
Comment (Minecraftschurli) [inline gradle.properties]: 1.1.0

File: src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/event/SpellEvent.java [hunk 2]
```diff
@@ -30,13 +30,31 @@ public ISpell getSpell() {
     }
 
     /**
-     * Event that fires before a spell is cast.
+     * Event that fires when a spell is cast. Has Pre and Post sub events.
      */
     @Cancelable
```
Comment (Minecraftschurli) [inline src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/event/SpellEvent.java]: Cancellable should be on Pre not on the abstract base

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/AffinityCommand.java [hunk 3]
```diff
@@ -86,7 +88,12 @@ private static int addAffinity(Collection<ServerPlayer> players, IAffinity affin
         double amount = DoubleArgumentType.getDouble(context, "amount");
         var helper = ArsMagicaAPI.get().getAffinityHelper();
         for (ServerPlayer player : players) {
-            helper.setAffinityDepth(player, affinity, (float) (helper.getAffinityDepth(player, affinity) + amount));
+            AffinityChangingEvent.Pre event = new AffinityChangingEvent.Pre(player, affinity, (float) amount, true);
+            MinecraftForge.EVENT_BUS.post(event);
+            if (!event.isCanceled()) {
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/AffinityCommand.java]: can be condensed (this is why IEventBus#post returns a boolean)

File: src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/AffinityCommand.java [hunk 4]
```diff
@@ -106,8 +113,14 @@ private static int setAffinity(CommandContext<CommandSourceStack> context) throw
 
     private static int setAffinity(Collection<ServerPlayer> players, IAffinity affinity, CommandContext<CommandSourceStack> context) {
         double amount = DoubleArgumentType.getDouble(context, "amount");
+        var helper = ArsMagicaAPI.get().getAffinityHelper();
         for (ServerPlayer player : players) {
-            ArsMagicaAPI.get().getAffinityHelper().setAffinityDepth(player, affinity, (float) amount);
+            AffinityChangingEvent.Pre event = new AffinityChangingEvent.Pre(player, affinity, (float) amount, true);
+            MinecraftForge.EVENT_BUS.post(event);
+            if (!event.isCanceled()) {
```
Comment (Minecraftschurli) [inline src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/server/commands/AffinityCommand.java]: again can be condensed

**Review by Minecraftschurli — CHANGES_REQUESTED** [review]
Some little thing still need to be improved

**Review by Minecraftschurli — APPROVED** [review]
Looks good (I hope it works too) :shipit:
