### PR TITLE
Fix #299

### LINKED ISSUE #299: [Bug]: Crash on joining a server. (Version 1.1.0)
### Describe the bug

When joining a server with the latest update, the client crashes almost immediately.

### Steps to Reproduce

-Join a server with the mod installed on both server and client
-Wait
-Client crash

### Expected behavior

_No response_

### Screenshots

_No response_

### Version

1.18.2-1.1.0

### Forge Version

40.1.25

### Other Mods

patchouli

### Log

```shell
[07:36:56] [main/INFO]: ModLauncher running: args [--username, Darth_Pikachu, --version, forge-40.1.25, --gameDir, C:\Users\Dart Pikachu\curseforge\minecraft\Instances\testreporting, --assetsDir, C:\Users\Dart Pikachu\curseforge\minecraft\Install\assets, --assetIndex, 1.18, --uuid, 64602d001b1b47aab69527e176bc01e9, --accessToken, ????????, --clientId, MTZjZWNkZTktMjc3Ny00ZWE0LWJhMWItMGZhYThlYWJlMWJh, --xuid, 2533274985511454, --userType, msa, --versionType, release, --width, 1024, --height, 768, --launchTarget, forgeclient, --fml.forgeVersion, 40.1.25, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[07:36:56] [main/INFO]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Microsoft
[07:36:57] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Dart%20Pikachu/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
[07:36:57] [main/INFO]: Found mod file arsmagicalegacy-1.18.2-1.1.0.jar of type MOD with locator {mods folder locator at C:\Users\Dart Pikachu\curseforge\minecraft\Instances\testreporting\mods}
[07:36:57] [main/INFO]: Found mod file Patchouli-1.18.2-67.jar of type MOD with locator {mods folder locator at C:\Users\Dart Pikachu\curseforge\minecraft\Instances\testreporting\mods}
[07:36:57] [main/INFO]: Found mod file fmlcore-1.18.2-40.1.25.jar of type LIBRARY with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3704122f
[07:36:57] [main/INFO]: Found mod file javafmllanguage-1.18.2-40.1.25.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3704122f
[07:36:57] [main/INFO]: Found mod file mclanguage-1.18.2-40.1.25.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3704122f
[07:36:57] [main/INFO]: Found mod file client-1.18.2-20220404.173914-srg.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3704122f
[07:36:57] [main/INFO]: Found mod file forge-1.18.2-40.1.25-universal.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3704122f
[07:36:59] [main/INFO]: Compatibility level set to JAVA_17
[07:36:59] [main/INFO]: Launching target 'forgeclient' with arguments [--version, forge-40.1.25, --gameDir, C:\Users\Dart Pikachu\curseforge\minecraft\Instances\testreporting, --assetsDir, C:\Users\Dart Pikachu\curseforge\minecraft\Install\assets, --uuid, 64602d001b1b47aab69527e176bc01e9, --username, Darth_Pikachu, --assetIndex, 1.18, --accessToken, ????????, --clientId, MTZjZWNkZTktMjc3Ny00ZWE0LWJhMWItMGZhYThlYWJlMWJh, --xuid, 2533274985511454, --userType, msa, --versionType, release, --width, 1024, --height, 768]
[07:37:01] [main/WARN]: Failed to add PDH Counter: \Paging File(_Total)\% Usage, Error code: 0xC0000BB8
[07:37:01] [main/WARN]: Failed to add counter for PDH counter: \Paging File(_Total)\% Usage
[07:37:01] [main/WARN]: Disabling further attempts to query Paging File.
[07:37:02] [main/WARN]: COM exception: Invalid Query: SELECT PERCENTUSAGE FROM Win32_PerfRawData_PerfOS_PagingFile
[07:37:09] [Render thread/WARN]: Assets URL 'union:/C:/Users/Dart%20Pikachu/curseforge/minecraft/Install/libraries/net/minecraft/client/1.18.2-20220404.173914/client-1.18.2-20220404.173914-srg.jar%2354!/assets/.mcassetsroot' uses unexpected schema
[07:37:09] [Render thread/WARN]: Assets URL 'union:/C:/Users/Dart%20Pikachu/curseforge/minecraft/Install/libraries/net/minecraft/client/1.18.2-20220404.173914/client-1.18.2-20220404.173914-srg.jar%2354!/data/.mcassetsroot' uses unexpected schema
[07:37:09] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[07:37:10] [Render thread/INFO]: Setting user: Darth_Pikachu
[07:37:10] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
[07:37:11] [modloading-worker-0/INFO]: Forge mod loading, version 40.1.25, for MC 1.18.2 with MCP 20220404.173914
[07:37:11] [modloading-worker-0/INFO]: MinecraftForge v40.1.25 Initialized
[07:37:12] [modloading-worker-0/ERROR]: Failed to load: com.github.minecraftschurlimods.arsmagicalegacy.compat.theoneprobe.TOPCompat
java.lang.NoClassDefFoundError: mcjty/theoneprobe/api/IProbeInfoProvider
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at com.github.minecraftschurlimods.arsmagicalegacy.compat.CompatManager.lambda$getClasses$1(CompatManager.java:117) ~[arsmagicalegacy-1.18.2-1.1.0.jar%2352!/:1.1.0]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at com.github.minecraftschurlimods.arsmagicalegacy.compat.CompatManager.getClasses(CompatManager.java:122) ~[arsmagicalegacy-1.18.2-1.1.0.jar%2352!/:1.1.0]
	at com.github.minecraftschurlimods.arsmagicalegacy.compat.CompatManager.discoverModCompats(CompatManager.java:104) ~[arsmagicalegacy-1.18.2-1.1.0.jar%2352!/:1.1.0]
	at com.github.minecraftschurlimods.arsmagicalegacy.compat.CompatManager.preInit(CompatManager.java:68) ~[arsmagicalegacy-1.18.2-1.1.0.jar%2352!/:1.1.0]
	at com.github.minecraftschurlimods.arsmagicalegacy.ArsMagicaLegacy.<init>(ArsMagicaLegacy.java:75) ~[arsmagicalegacy-1.18.2-1.1.0.jar%2352!/:1.1.0]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.25.jar%2356!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.25.jar%2355!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.ClassNotFoundException: mcjty.theoneprobe.api.IProbeInfoProvider
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 37 more
[07:37:14] [Render thread/INFO]: Narrator library for x64 successfully loaded
[07:37:15] [Render thread/INFO]: Reloading ResourceManager: Default, Mod Resources
[07:37:15] [modloading-worker-0/WARN]: Configuration file C:\Users\Dart Pikachu\curseforge\minecraft\Instances\testreporting\config\patchouli-client.toml is not correct. Correcting
[07:37:15] [modloading-worker-0/WARN]: Incorrect key noAdvancementBooks was corrected from [] to its default, []. 
[07:37:18] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[07:37:19] [Forge Version Check/INFO]: [forge] Found status: AHEAD Current: 40.1.25 Target: null
[07:37:25] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers (Realtek High Definition Audio)
[07:37:25] [Render thread/INFO]: Sound engine started
[07:37:25] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[07:37:25] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[07:37:25] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[07:37:25] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[07:37:25] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[07:37:25] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[07:37:25] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[07:37:27] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[07:37:27] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[07:37:27] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[07:37:27] [Render thread/INFO]: Created: 1024x512x0 arsmagicalegacy:textures/atlas/spell_icons.png-atlas
[07:37:27] [Render thread/INFO]: Created: 1024x512x0 arsmagicalegacy:textures/atlas/skill_icons.png-atlas
[07:37:27] [Render thread/INFO]: BookContentResourceListenerLoader preloaded 189 jsons
[07:37:27] [Render thread/INFO]: Not reloading resource pack-based books as client world is missing
[07:38:55] [Render thread/INFO]: Connecting to 24.124.67.129, 25565
[07:38:57] [Render thread/INFO]: Injecting existing registry data into this CLIENT instance
[07:38:58] [Netty Client IO #2/INFO]: Connected to a modded server.
[07:39:01] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[07:39:01] [Render thread/ERROR]: Error executing task on Client
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.github.minecraftschurlimods.simplenetlib.NetworkHandler$ThrowingFunction.apply(NetworkHandler.java:391) ~[arsmagicalegacy-1.18.2-1.1.0.jar%2352!/:1.1.0]
	at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryDecode$0(IndexedMessageCodec.java:106) ~[forge-1.18.2-40.1.25-universal.jar%2358!/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:106) ~[forge-1.18.2-40.1.25-universal.jar%2358!/:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:148) ~[forge-1.18.2-40.1.25-universal.jar%2358!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:68) ~[forge-1.18.2-40.1.25-universal.jar%2358!/:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:68) ~[forge-1.18.2-40.1.25-universal.jar%2358!/:?]
	at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:75) ~[forge-1.18.2-40.1.25-universal.jar%2358!/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:75) ~[forge-1.18.2-40.1.25-universal.jar%2358!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_7413_(ClientPacketListener.java:1824) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket.m_5797_(ClientboundCustomPayloadPacket.java:57) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket.m_5797_(ClientboundCustomPayloadPacket.java:7) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1013) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.25.jar%2316!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.github.minecraftschurlimods.simplenetlib.NetworkHandler.lambda$register$8(NetworkHandler.java:366) ~[arsmagicalegacy-1.18.2-1.1.0.jar%2352!/:1.1.0]
	at com.github.minecraftschurlimods.simplenetlib.NetworkHandler$ThrowingFunction.apply(NetworkHandler.java:389) ~[arsmagicalegacy-1.18.2-1.1.0.jar%2352!/:1.1.0]
	... 37 more
Caused by: java.lang.NullPointerException: Cannot read field "networkCodec" because the return value of "com.github.minecraftschurlimods.codeclib.CodecDataManager$SyncPacket.getDataManager()" is null
	at com.github.minecraftschurlimods.codeclib.CodecDataManager$SyncPacket.<init>(CodecDataManager.java:204) ~[arsmagicalegacy-1.18.2-1.1.0.jar%2352!/:1.1.0]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.github.minecraftschurlimods.simplenetlib.NetworkHandler.lambda$register$8(NetworkHandler.java:366) ~[arsmagicalegacy-1.18.2-1.1.0.jar%2352!/:1.1.0]
	at com.github.minecraftschurlimods.simplenetlib.NetworkHandler$ThrowingFunction.apply(NetworkHandler.java:389) ~[arsmagicalegacy-1.18.2-1.1.0.jar%2352!/:1.1.0]
	... 37 more
[07:39:15] [Render thread/INFO]: Loaded 0 advancements
[07:39:15] [Render thread/INFO]: BookContentResourceListenerLoader: Files found in 336.2 ?s
[07:39:15] [Render thread/INFO]: BookContentResourceListenerLoader: Files found in 296.1 ?s
[07:39:15] [Render thread/INFO]: BookContentResourceListenerLoader: Files found in 202.5 ?s
[07:39:27] [Render thread/ERROR]: Throwing
java.util.NoSuchElementException: null
	at com.github.minecraftschurlimods.codeclib.CodecDataManager.getOrThrow(CodecDataManager.java:109) ~[arsmagicalegacy-1.18.2-1.1.0.jar%2352!/:1.1.0]
	at com.github.minecraftschurlimods.arsmagicalegacy.common.ability.AbilityManager.get(AbilityManager.java:63) ~[arsmagicalegacy-1.18.2-1.1.0.jar%2352!/:1.1.0]
	at com.github.minecraftschurlimods.arsmagicalegacy.common.ability.AbilityManager.get(AbilityManager.java:25) ~[arsmagicalegacy-1.18.2-1.1.0.jar%2352!/:1.1.0]
	at com.github.minecraftschurlimods.arsmagicalegacy.common.handler.AbilityHandler.livingJump(AbilityHandler.java:115) ~[arsmagicalegacy-1.18.2-1.1.0.jar%2352!/:1.1.0]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.common.ForgeHooks.onLivingJump(ForgeHooks.java:400) ~[forge-1.18.2-40.1.25-universal.jar%2358!/:?]
	at net.minecraft.world.entity.LivingEntity.m_6135_(LivingEntity.java:1976) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.world.entity.player.Player.m_6135_(Player.java:1369) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2525) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.world.entity.player.Player.m_8107_(Player.java:492) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.player.LocalPlayer.m_8107_(LocalPlayer.java:759) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2253) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:235) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.player.LocalPlayer.m_8119_(LocalPlayer.java:183) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.multiplayer.ClientLevel.m_104639_(ClientLevel.java:222) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:486) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.multiplayer.ClientLevel.m_194182_(ClientLevel.java:204) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.multiplayer.ClientLevel.m_104804_(ClientLevel.java:202) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1691) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1019) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.25.jar%2316!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
[07:39:27] [Render thread/ERROR]: Exception caught during firing event: null
	Index: 2
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$4276/0x0000000800b960e8@5a1c0bcc
		2: net.minecraftforge.eventbus.EventBus$$Lambda$4276/0x0000000800b960e8@4f8eb97c
java.util.NoSuchElementException
	at TRANSFORMER/arsmagicalegacy@1.18.2-1.1.0/com.github.minecraftschurlimods.codeclib.CodecDataManager.getOrThrow(CodecDataManager.java:109)
	at TRANSFORMER/arsmagicalegacy@1.18.2-1.1.0/com.github.minecraftschurlimods.arsmagicalegacy.common.ability.AbilityManager.get(AbilityManager.java:63)
	at TRANSFORMER/arsmagicalegacy@1.18.2-1.1.0/com.github.minecraftschurlimods.arsmagicalegacy.common.ability.AbilityManager.get(AbilityManager.java:25)
	at TRANSFORMER/arsmagicalegacy@1.18.2-1.1.0/com.github.minecraftschurlimods.arsmagicalegacy.common.handler.AbilityHandler.livingJump(AbilityHandler.java:115)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@40.1.25/net.minecraftforge.common.ForgeHooks.onLivingJump(ForgeHooks.java:400)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.LivingEntity.m_6135_(LivingEntity.java:1976)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.player.Player.m_6135_(Player.java:1369)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2525)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.player.Player.m_8107_(Player.java:492)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.player.LocalPlayer.m_8107_(LocalPlayer.java:759)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2253)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.player.Player.m_8119_(Player.java:235)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.player.LocalPlayer.m_8119_(LocalPlayer.java:183)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.multiplayer.ClientLevel.m_104639_(ClientLevel.java:222)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.Level.m_46653_(Level.java:486)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.multiplayer.ClientLevel.m_194182_(ClientLevel.java:204)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.multiplayer.ClientLevel.m_104804_(ClientLevel.java:202)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1691)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1019)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.25/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)

[07:39:28] [Render thread/WARN]: COM exception: Invalid Query: SELECT PERCENTUSAGE FROM Win32_PerfRawData_PerfOS_PagingFile
[07:39:29] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.ReportedException: Ticking entity
	at net.minecraft.world.level.Level.m_46653_(Level.java:495) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.multiplayer.ClientLevel.m_194182_(ClientLevel.java:204) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.multiplayer.ClientLevel.m_104804_(ClientLevel.java:202) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1691) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1019) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.25.jar%2316!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: java.util.NoSuchElementException
	at com.github.minecraftschurlimods.codeclib.CodecDataManager.getOrThrow(CodecDataManager.java:109) ~[arsmagicalegacy-1.18.2-1.1.0.jar%2352!/:1.1.0]
	at com.github.minecraftschurlimods.arsmagicalegacy.common.ability.AbilityManager.get(AbilityManager.java:63) ~[arsmagicalegacy-1.18.2-1.1.0.jar%2352!/:1.1.0]
	at com.github.minecraftschurlimods.arsmagicalegacy.common.ability.AbilityManager.get(AbilityManager.java:25) ~[arsmagicalegacy-1.18.2-1.1.0.jar%2352!/:1.1.0]
	at com.github.minecraftschurlimods.arsmagicalegacy.common.handler.AbilityHandler.livingJump(AbilityHandler.java:115) ~[arsmagicalegacy-1.18.2-1.1.0.jar%2352!/:1.1.0]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.common.ForgeHooks.onLivingJump(ForgeHooks.java:400) ~[forge-1.18.2-40.1.25-universal.jar%2358!/:?]
	at net.minecraft.world.entity.LivingEntity.m_6135_(LivingEntity.java:1976) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.world.entity.player.Player.m_6135_(Player.java:1369) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2525) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.world.entity.player.Player.m_8107_(Player.java:492) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.player.LocalPlayer.m_8107_(LocalPlayer.java:759) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2253) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:235) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.player.LocalPlayer.m_8119_(LocalPlayer.java:183) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.multiplayer.ClientLevel.m_104639_(ClientLevel.java:222) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:486) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	... 20 more
[07:39:29] [Render thread/FATAL]: Preparing crash report with UUID fcedb6b8-7ca3-440a-a94c-7e761b628f78
[07:39:29] [Render thread/FATAL]: Preparing crash report with UUID 7df9db63-a47f-4a14-a624-4bcada90674e
```

### PR DESCRIPTION
**Pull request by Minecraftschurli**
Fixes #299

### CODE REVIEW

**Review by IchHabeHunger54 — DISMISSED** [review]

**Review by IchHabeHunger54 — DISMISSED** [review]

File: src/data/java/com/github/minecraftschurlimods/arsmagicalegacy/data/AMPatchouliBookProvider.java [hunk 1]
```diff
@@ -300,14 +298,21 @@ protected void addBooks(Consumer<BookBuilder<?, ?, ?>> consumer) {
...
+        affinities.addEntry("affinities", "Affinities", affinityHelper.getEssenceForAffinity(IAffinity.WATER))
+                .setPriority(true)
+                .addSimpleTextPage("Affinities are magical elements of sorts. All components (excluding some of the very powerful, reality-bending ones) have an affinity that is associated with them. That means that if you use spells with a certain affinity a lot, you will shift into that affinity.")
+                .addSimpleTextPage("Shifting into an affinity bears individual side effects, called abilities. Each affinity has different abilities. You can read about the abilities for each affinity in the dedicated chapters for them.$(br2)If you wish to see your current shift into an affinity, you can view your shifts in the Affinity tab of the $(l:blocks/occulus)Occulus$().")
+                .addSimpleTextPage("There is also an affinity essence for each affinity, which is used in intermediate crafting for spell parts associated with that affinity. Reports about lost affinity tomes have been spreading as well, though how to obtain or use them is currently subject to investigation.")
+                .build();
```
Comment (Minecraftschurli) [inline src/data/java/com/github/minecraftschurlimods/arsmagicalegacy/data/AMPatchouliBookProvider.java]: Nope.... This won't look good 2 entries with the same item as icon also an additional entry where a category description would suffice

File: src/data/java/com/github/minecraftschurlimods/arsmagicalegacy/data/AMPatchouliBookProvider.java [hunk 2]
```diff
@@ -300,14 +298,21 @@ protected void addBooks(Consumer<BookBuilder<?, ?, ?>> consumer) {
...
         var abilityRegistry = api.getAbilityRegistry();
         for (final IAffinity affinity : api.getAffinityRegistry()) {
             ResourceLocation id = affinity.getId();
             if (!id.getNamespace().equals(builder.getId().getNamespace()) || id.equals(IAffinity.NONE)) continue;
-            TranslatedEntryBuilder entry = affinities.addEntry(id.getPath(), affinity.getTranslationKey(), affinityHelper.getEssenceForAffinity(affinity))
-                                                     .addSimpleSpotlightPage(affinityHelper.getEssenceForAffinity(affinity), null, affinity.getTranslationKey())
-                                                     .addSimpleRecipePage("crafting", new ResourceLocation(id.getNamespace(), "affinity_essence_" + id.getPath()));
+            TranslatedEntryBuilder entry = affinities.addEntry(id.getPath(), affinity.getTranslationKey(), affinityHelper.getEssenceForAffinity(affinity));
+            entry.addSimpleTextPage(entry.getLangKey(0) + ".text");
+            entry.addSimpleRecipePage("crafting", new ResourceLocation(id.getNamespace(), "affinity_essence_" + id.getPath()));
```
Comment (Minecraftschurli) [inline src/data/java/com/github/minecraftschurlimods/arsmagicalegacy/data/AMPatchouliBookProvider.java:315]: Why no spotlight? The recipe is temporary anyway and the highlight looks good

**Review by Minecraftschurli — COMMENTED** [review]
Not quite ready

File: src/data/java/com/github/minecraftschurlimods/arsmagicalegacy/data/AMPatchouliBookProvider.java (hunk 1 above)
Comment (IchHabeHunger54) [reply src/data/java/com/github/minecraftschurlimods/arsmagicalegacy/data/AMPatchouliBookProvider.java]: Category description is too large and invasive imo; and I'm open to suggestions for a better icon.

File: src/data/java/com/github/minecraftschurlimods/arsmagicalegacy/data/AMPatchouliBookProvider.java (hunk 2 above)
Comment (IchHabeHunger54) [reply src/data/java/com/github/minecraftschurlimods/arsmagicalegacy/data/AMPatchouliBookProvider.java:315]: My idea was to re-add the spotlight once the recipes were removed (bosses should be finished this week anyway)

File: src/data/java/com/github/minecraftschurlimods/arsmagicalegacy/data/AMPatchouliBookProvider.java (hunk 1 above)
Comment (Minecraftschurli) [reply src/data/java/com/github/minecraftschurlimods/arsmagicalegacy/data/AMPatchouliBookProvider.java]: If you think so ...
Use a nether star for now

File: src/data/java/com/github/minecraftschurlimods/arsmagicalegacy/data/AMPatchouliBookProvider.java (hunk 2 above)
Comment (Minecraftschurli) [reply src/data/java/com/github/minecraftschurlimods/arsmagicalegacy/data/AMPatchouliBookProvider.java:315]: fine

**Review by IchHabeHunger54 — APPROVED** [review]
